### ISSUE TITLE
Camera init failed

### ISSUE THREAD

**Issue by jbkim** [nabto/nabto-esp32cam#2] opened 2019-06-27 06:45 UTC
HI,

I changed the pin configuration as below to test with [ESP32cam](https://docs.m5stack.com/#/en/unit/esp32cam). 

~~~cpp
#define CAM_PIN_PWDN    -1 //power down is not used
#define CAM_PIN_RESET   15 
#define CAM_PIN_XCLK    27
#define CAM_PIN_SIOD    25
#define CAM_PIN_SIOC    23

#define CAM_PIN_D7      19
#define CAM_PIN_D6      36
#define CAM_PIN_D5      18
#define CAM_PIN_D4      39
#define CAM_PIN_D3       5
#define CAM_PIN_D2      34
#define CAM_PIN_D1      35
#define CAM_PIN_D0      17
#define CAM_PIN_VSYNC   22
#define CAM_PIN_HREF    26
#define CAM_PIN_PCLK    21
~~~

and got error message while booting.

> D (987) camera: Searching for camera address
> D (1007) camera: Detected camera at address=0x3c
> D (1017) camera: Camera PID=0xff VER=0xff
> E (1017) camera: Detected camera not supported.
> E (1017) camera: Camera probe failed with error 0x20004

Do I need to make any other change in the source?
The weird thing is below code works well with Arduino IDE.

~~~cpp
#include "esp_camera.h"

#define CAM_PIN_PWDN    -1 //power down is not used
#define CAM_PIN_RESET   15 //software reset will be performed
#define CAM_PIN_XCLK    27
#define CAM_PIN_SIOC    23
#define CAM_PIN_SIOD    25

#define CAM_PIN_HREF    26
#define CAM_PIN_PCLK    21

#define CAM_PIN_D7      19
#define CAM_PIN_D6      36
#define CAM_PIN_D5      18
#define CAM_PIN_D4      39
#define CAM_PIN_D3      5
#define CAM_PIN_D2      34
#define CAM_PIN_D1      35
#define CAM_PIN_D0      17

#define CAM_XCLK_FREQ   10000000
#define CAMERA_LED_GPIO 16
#define CAM_PIN_VSYNC   22

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();

  static camera_config_t config = {
    .pin_pwdn  = CAM_PIN_PWDN,
    .pin_reset = CAM_PIN_RESET,
    .pin_xclk = CAM_PIN_XCLK,
    .pin_sscb_sda = CAM_PIN_SIOD,
    .pin_sscb_scl = CAM_PIN_SIOC,

    .pin_d7 = CAM_PIN_D7,
    .pin_d6 = CAM_PIN_D6,
    .pin_d5 = CAM_PIN_D5,
    .pin_d4 = CAM_PIN_D4,
    .pin_d3 = CAM_PIN_D3,
    .pin_d2 = CAM_PIN_D2,
    .pin_d1 = CAM_PIN_D1,
    .pin_d0 = CAM_PIN_D0,
    .pin_vsync = CAM_PIN_VSYNC,
    .pin_href = CAM_PIN_HREF,
    .pin_pclk = CAM_PIN_PCLK,

    //XCLK 20MHz or 10MHz for OV2640 double FPS (Experimental)
    // .xclk_freq_hz = 20000000,
    .xclk_freq_hz = CAM_XCLK_FREQ,    
    .ledc_timer = LEDC_TIMER_0,
    .ledc_channel = LEDC_CHANNEL_0,

    .pixel_format = PIXFORMAT_JPEG,//YUV422,GRAYSCALE,RGB565,JPEG
    .frame_size = FRAMESIZE_VGA,//QQVGA-QXGA Do not use sizes above QVGA when not JPEG

    .jpeg_quality = 10, //0-63 lower number means higher quality
    .fb_count = 2 //if more than one, i2s runs in continuous mode. Use only with JPEG
};

  // camera init
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }

  //drop down frame size for higher initial frame rate
  sensor_t * s = esp_camera_sensor_get();
  s->set_framesize(s, FRAMESIZE_QVGA);  

  Serial.printf("Camera init completed !!");
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(10000);
} 
~~~

**Comment by crgregersen** [comment] 2019-06-27 07:10
Hi,

Yes, we have had the same issues.

In the reset part of "camera.c" .. i.e. line 960 if clause starting with:
960     if(config->pin_reset >= 0) {

Try to reverse the GPIO level setting.. i.e. from 1 to 0 instead of 0 to 1.

 968         gpio_set_level(config->pin_reset, 1);

Probably we need a hardware expert to loook at this... it looks like the reset PIN is reversed on the Ai Tinker board.

/Carsten

**Comment by crgregersen** [comment] 2019-06-27 07:11
Please inform us if you manage it to run, so we can close the issue :-)

**Comment by jbkim** [comment] 2019-06-27 08:37
After changing the GPIO reset level, the camera is initialized. :)

Now I can see the image on the web browser but failed to see it with app.
- Pairing the video app with the wifi module is ok: I can see the green mark on the camera logo.
- After click it, "Cannot show video" message was displayed.

Below is the terminal message.
~~~cpp
00:09:34:274 unabto_application.c(37) Access control list dump:
00:09:34:275 unabto_application.c(51) JbiPhone [84:08:d9:1a:...]: e0000000
00:09:34:276 unabto_application.c(141) Nabto application_event: 10000
00:09:34:300 unabto_application.c(37) Access control list dump:
00:09:34:302 unabto_application.c(51) JbiPhone [84:08:d9:1a:...]: e0000000
00:09:34:302 unabto_application.c(141) Nabto application_event: 0
00:09:44:308 unabto_tunnel.c(37) Allow connection host:127.0.0.1 port:8081
00:09:44:309 unabto_tunnel_tcp.c(299) Tunnel(9) connecting to 127.0.0.1:8081
00:09:44:312 unabto_tcp.c(88) fcntl failed in F_GETFL
00:09:44:317 unabto_tunnel_tcp.c(191) Open socket failed
00:09:44:612 unabto_tunnel_tcp.c(88) Tunnel(9) closed, sentPackets: 5, sentBytes 0, sentResentPackets 0, receivedPackets 6, receivedBytes 502, receivedResentPackets 0, reorderedOrLostPackets 0, timeouts 0, rtt avg 0, cwnd avg 0, ssthreshold avg 60, flightSize avg 0, sendSegmentAllocFailures 0, recvWindowSize 10, recvSegmentSize 1247, sendWindowSize 60, sendSegmentSize 1247
00:09:44:634 unabto_tunnel.c(56) Tunnel event [1] on tunnel [9] to host [127.0.0.1] on port [8081], bytes sent: [0]
00:09:44:644 unabto_tcp.c(54) trying to close invalid socket
00:09:45:841 unabto_tunnel.c(37) Allow connection host:127.0.0.1 port:8081
00:09:45:842 unabto_tunnel_tcp.c(299) Tunnel(10) connecting to 127.0.0.1:8081
00:09:45:845 unabto_tcp.c(88) fcntl failed in F_GETFL
00:09:45:849 unabto_tunnel_tcp.c(191) Open socket failed
00:09:47:166 unabto_tunnel_tcp.c(88) Tunnel(10) closed, sentPackets: 5, sentBytes 0, sentResentPackets 0, receivedPackets 6, receivedBytes 502, receivedResentPackets 0, reorderedOrLostPackets 0, timeouts 0, rtt avg 0, cwnd avg 0, ssthreshold avg 60, flightSize avg 0, sendSegmentAllocFailures 0, recvWindowSize 10, recvSegmentSize 1247, sendWindowSize 60, sendSegmentSize 1247
00:09:47:188 unabto_tunnel.c(56) Tunnel event [1] on tunnel [10] to host [127.0.0.1] on port [8081], bytes sent: [0]
00:09:47:198 unabto_tcp.c(54) trying to close invalid socket
00:09:48:019 unabto_tunnel.c(37) Allow connection host:127.0.0.1 port:8081
00:09:48:020 unabto_tunnel_tcp.c(299) Tunnel(11) connecting to 127.0.0.1:8081
00:09:48:023 unabto_tcp.c(88) fcntl failed in F_GETFL
00:09:48:028 unabto_tunnel_tcp.c(191) Open socket failed
00:09:48:052 unabto_tunnel_tcp.c(88) Tunnel(11) closed, sentPackets: 5, sentBytes 0, sentResentPackets 0, receivedPackets 6, receivedBytes 502, receivedResentPackets 0, reorderedOrLostPackets 0, timeouts 0, rtt avg 0, cwnd avg 0, ssthreshold avg 60, flightSize avg 0, sendSegmentAllocFailures 0, recvWindowSize 10, recvSegmentSize 1247, sendWindowSize 60, sendSegmentSize 1247
00:09:48:075 unabto_tunnel.c(56) Tunnel event [1] on tunnel [11] to host [127.0.0.1] on port [8081], bytes sent: [0]
00:09:48:085 unabto_tcp.c(54) trying to close invalid socket
~~~

**Comment by crgregersen** [comment] 2019-06-27 08:44
Try 
make menuconfig
Component->LWIP->”Support per-interface-loopback”

Is this set?
Maybe something has changed in the IDF default configuration.

/Carsten

**Comment by jbkim** [comment] 2019-06-27 09:03
Component->LWIP->”Support per-interface-loopback” was already set.

**Comment by crgregersen** [comment] 2019-06-27 09:09
Ok. The problem is fnctl .. it seems like the system cannot read the current flags..
This is certainly a problem.. and it's a problem in the system. The theory is that something changed in the ESP-IDF.

Please do a:
~/esp/esp-idf$ git describe --tags --dirty
v4.0-dev-459-gba1ff1692

**Comment by jbkim** [comment] 2019-06-27 09:19
In my system:
~/esp/esp-idf$ git describe --tags --dirty
v4.0-dev-837-g58df1d93b

**Comment by crgregersen** [comment] 2019-06-27 09:26
Could you try to downgrade your ESP-IDF environment?

(i think it's like this.. not a git expert)
cd $IDF_PATH
git fetch
git checkout v4.0-dev-459-gba1ff1692
git submodule update --init --recursive

**Comment by jbkim** [comment] 2019-06-27 09:55
No success. :(

**Comment by crgregersen** [comment] 2019-06-27 11:16
Hmm... we can reproduce your findings here.
IDF-ESP environment "stable" version works. Currently "latest" doesn't ..!!! We don't know when this happened to "latest" but it is safest to use stable.

For example MacOS:
Works: xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz
Doesn't work: xtensa-esp32-elf-gcc8_2_0-esp32-2019r1-macos.tar.gz

I'm not sure if you use Windows, Linux or MacOS, but our guess is that this is the same issue (since the fcntl is bootstrapped in closed code, i.e. "extern", so it's probably same firmware supplied by Expressif)

I.e. please setup ESP-IDF by following:
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/windows-setup.html
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup.html
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/macos-setup.html

**Comment by crgregersen** [comment] 2019-06-27 12:25
Has been reproduced and fixed by using "stable" release by other user than reporter.
Issue reported to Epressif:
https://github.com/espressif/esp-idf/issues/3694

**Closed as completed by crgregersen** 2019-06-27 12:25 UTC

**Comment by jbkim** [comment] 2019-06-27 14:52
Thanks! I'll try it again.

**Comment by jbkim** [comment] 2019-06-27 15:13
It works! ;)
